// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat/:id": {
    params: {
      "id": string;
    };
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat/:id" | "/test";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/chat.$id.tsx": {
    id: "routes/chat.$id";
    page: "/chat/:id";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/chat.$id": typeof import("./app/routes/chat.$id.tsx");
  "routes/test": typeof import("./app/routes/test.tsx");
};